// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Climate

lv_obj_t * ui_Climate_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Climate;
    cui_Climate = lv_label_create(comp_parent);
    lv_obj_set_width(cui_Climate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Climate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Climate, -7);
    lv_obj_set_y(cui_Climate, -103);
    lv_obj_set_align(cui_Climate, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Climate, "Climate Control");
    lv_obj_set_style_text_color(cui_Climate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Climate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CLIMATE_NUM);
    children[UI_COMP_CLIMATE_CLIMATE] = cui_Climate;
    lv_obj_add_event_cb(cui_Climate, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Climate, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Climate_create_hook(cui_Climate);
    return cui_Climate;
}

