// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_main, &ui_img_new_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_main, &ui_img_new_png, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_main);
    lv_obj_set_width(ui_Arc1, 125);
    lv_obj_set_height(ui_Arc1, 120);
    lv_obj_set_x(ui_Arc1, -87);
    lv_obj_set_y(ui_Arc1, 1);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);


    ui_Switch1 = lv_switch_create(ui_main);
    lv_obj_set_width(ui_Switch1, 60);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -90);
    lv_obj_set_y(ui_Switch1, 95);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Climate1 = lv_label_create(ui_main);
    lv_obj_set_width(ui_Climate1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Climate1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Climate1, 3);
    lv_obj_set_y(ui_Climate1, -107);
    lv_obj_set_align(ui_Climate1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Climate1, "Climate Control");
    lv_obj_set_style_text_color(ui_Climate1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Climate1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Climate1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Climate1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FANSPD = lv_label_create(ui_main);
    lv_obj_set_width(ui_FANSPD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FANSPD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FANSPD, -90);
    lv_obj_set_y(ui_FANSPD, 1);
    lv_obj_set_align(ui_FANSPD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FANSPD, "%50");
    lv_obj_set_style_text_color(ui_FANSPD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FANSPD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_main);
    lv_obj_set_width(ui_Arc2, 128);
    lv_obj_set_height(ui_Arc2, 124);
    lv_obj_set_x(ui_Arc2, 93);
    lv_obj_set_y(ui_Arc2, 3);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc2, 18, 35);
    lv_arc_set_value(ui_Arc2, 23);


    ui_Label3 = lv_label_create(ui_main);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -89);
    lv_obj_set_y(ui_Label3, 66);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "FAN SPEED");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_main);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 92);
    lv_obj_set_y(ui_Label4, 65);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "A/C");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_main);
    lv_obj_set_width(ui_Switch2, 60);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 94);
    lv_obj_set_y(ui_Switch2, 95);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);


    ui_TEMP = lv_label_create(ui_main);
    lv_obj_set_width(ui_TEMP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TEMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEMP, 91);
    lv_obj_set_y(ui_TEMP, 5);
    lv_obj_set_align(ui_TEMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEMP, "24 C");
    lv_obj_set_style_text_color(ui_TEMP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TEMP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ONOFF = lv_btn_create(ui_main);
    lv_obj_set_width(ui_ONOFF, 92);
    lv_obj_set_height(ui_ONOFF, 38);
    lv_obj_set_x(ui_ONOFF, 0);
    lv_obj_set_y(ui_ONOFF, 95);
    lv_obj_set_align(ui_ONOFF, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ONOFF, lv_color_hex(0x00CD06), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ONOFF, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ONOFFTXT = lv_label_create(ui_main);
    lv_obj_set_width(ui_ONOFFTXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ONOFFTXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ONOFFTXT, 0);
    lv_obj_set_y(ui_ONOFFTXT, 96);
    lv_obj_set_align(ui_ONOFFTXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ONOFFTXT, "ON/OFF");

    ui_VALABEL = lv_label_create(ui_main);
    lv_obj_set_width(ui_VALABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VALABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VALABEL, -110);
    lv_obj_set_y(ui_VALABEL, -100);
    lv_obj_set_align(ui_VALABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VALABEL, "Volt / Amper");
    lv_obj_set_style_text_color(ui_VALABEL, lv_color_hex(0x000FDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VALABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VALABEL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_main);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 116);
    lv_obj_set_y(ui_Label2, -97);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "POWER");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000FDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_main);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -112);
    lv_obj_set_y(ui_Label5, -79);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "120V/20A");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000FDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_main);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 116);
    lv_obj_set_y(ui_Label6, -78);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "2400W");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x000FDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ROOMTEMP = lv_label_create(ui_main);
    lv_obj_set_width(ui_ROOMTEMP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ROOMTEMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ROOMTEMP, 3);
    lv_obj_set_y(ui_ROOMTEMP, -78);
    lv_obj_set_align(ui_ROOMTEMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ROOMTEMP, "TEMPARATURE");
    lv_obj_set_style_text_color(ui_ROOMTEMP, lv_color_hex(0x000FDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ROOMTEMP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_main);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 2);
    lv_obj_set_y(ui_Label7, -54);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "30C");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000FDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Arc1, ui_event_Arc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc2, ui_event_Arc2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ONOFF, ui_event_ONOFF, LV_EVENT_ALL, NULL);

}
