// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_main
void ui_main_screen_init(void);
extern lv_obj_t * ui_main;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Climate1;
extern lv_obj_t * ui_FANSPD;
void ui_event_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_TEMP;
void ui_event_ONOFF(lv_event_t * e);
extern lv_obj_t * ui_ONOFF;
extern lv_obj_t * ui_ONOFFTXT;
extern lv_obj_t * ui_VALABEL;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_ROOMTEMP;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_new_png);    // assets/NEW.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
