// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
uint8_t Toggle = 0;
uint16_t FAN_SPD;
uint16_t HEAT_TAR;
void fan_on_1(lv_event_t * e)
{
	if (lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED))
	{
		CDC_Transmit_FS("FAN ON\n", strlen("FAN ON\n"));
	}

	else
	{
		CDC_Transmit_FS("FAN OFF\n", strlen("FAN OFF\n"));
	}
}

void AC_ON_OFF(lv_event_t * e)
{
	if (lv_obj_has_state(ui_Switch2, LV_STATE_CHECKED))
	{
		CDC_Transmit_FS("AC ON\n", strlen("AC ON\n"));
	}

	else
	{
		CDC_Transmit_FS("AC OFF\n", strlen("AC OFF\n"));
	}
}

void ONOFFBTNclicked(lv_event_t * e)
{
	Toggle++;
	if(Toggle==1){
		CDC_Transmit_FS("CLIMATE ON\n", strlen("CLİMATE ON\n"));
		lv_label_set_text(ui_ONOFFTXT, "ON");
	}
	else if(Toggle==2){
		CDC_Transmit_FS("CLIMATE OFF\n", strlen("CLİMATE OFF\n"));
		lv_label_set_text(ui_ONOFFTXT, "OFF");
	    Toggle=0;
	}
}

void FAN_SPD_CHAN(lv_event_t * e)
{
	FAN_SPD = lv_arc_get_value(ui_Arc1);
	char str="FAN SPEED: 100\n";
	sprintf(str,"FAN SPEED: %d\n", FAN_SPD);
	CDC_Transmit_FS(str, strlen(str));
}

void HEAT_CHANGE(lv_event_t * e)
{
	HEAT_TAR = lv_arc_get_value(ui_Arc2);
	char str[] = "HEAT: 25\n";
	sprintf(str,"HEAT: %d\n", HEAT_TAR);
	CDC_Transmit_FS(str, strlen(str));
}
