// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void FAN_SPD_CHAN(lv_event_t * e);
void fan_on_1(lv_event_t * e);
void HEAT_CHANGE(lv_event_t * e);
void AC_ON_OFF(lv_event_t * e);
void ONOFFBTNclicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
